[build-system]
requires = ["setuptools >= 61.0", "autosemver"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "boto3",
    "autosemver",
    "config",
    "awscli",
    "awscrt",
    "awsiot",
    "oracledb",
    "platformdirs",
]
name = "iot-device-simulator"
dynamic = ["version"]
authors = [{ name = "Lewis Chambers", email = "lewcha@ceh.ac.uk" }]
description = "Package for simulating a net of IoT devices for stress testing."

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pytest-asyncio", "parameterized"]

[tool.setuptools.dynamic]
version = { attr = "iotdevicesimulator.__version__" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["iotdevicesimulator"]

[tool.pytest.ini_options]

filterwarnings = [
    "ignore::DeprecationWarning:autosemver.*:",
    "ignore::DeprecationWarning:pkg_resources.*:",
]
addopts = "--cov=iotdevicesimulator"
markers = [
    "asyncio: Tests asynchronous functions.",
    "oracle: Requires oracle connection and required config credentials",
]
