[build-system]
requires = ["setuptools >= 61.0", "autosemver"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "platformdirs",
    "boto3",
    "autosemver",
    "config",
    "docutils<0.17",
    "awscli",
    "awscrt",
    "oracledb",
    "backoff",
]
name = "iot-device-simulator"
dynamic = ["version"]
authors = [{ name = "Lewis Chambers", email = "lewcha@ceh.ac.uk" }]
description = "Package for simulating a net of IoT devices for stress testing."

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pytest-asyncio", "parameterized"]
docs = ["sphinx", "sphinx-copybutton", "sphinx-rtd-theme"]

[project.scripts]
iot-swarm = "iotdevicesimulator.scripts.cli:main"
[tool.setuptools.dynamic]
version = { attr = "iotdevicesimulator.__version__" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.pytest.ini_options]

filterwarnings = [
    "ignore::DeprecationWarning:autosemver.*:",
    "ignore::DeprecationWarning:pkg_resources.*:",
]
addopts = "--cov=iotdevicesimulator"
markers = [
    "asyncio: Tests asynchronous functions.",
    "oracle: Requires oracle connection and required config credentials",
    "slow: Marks slow tests",
]

[tool.coverage.run]
omit = ["*example.py", "*__init__.py", "queries.py", "loggers.py"]
