# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on: [workflow_call]

permissions:
  contents: read

jobs:  
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Build Docs
        run: |
          python -c "import iotdevicesimulator; print(iotdevicesimulator.__version__)"
          pushd docs
          . ./make.sh build