name: Create release

on:
  push:
    branches: ["documentation"]

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          git fetch --unshallow origin +refs/heads/${{ github.ref_name }}:refs/remotes/origin/${{ github.ref_name }}
          git describe --long
          tag=$(python -c "import iotdevicesimulator; print(iotdevicesimulator.__version__)")
          echo $tag
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes