name: Test Package

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  docs:
    uses: ./.github/workflows/doc-test.yml
    if: ${{ (github.event_name == 'pull_request' && github.head_ref != 'main') || (github.event_name == 'push' && github.ref_name != 'main') }}